# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Zero Downtime Chris'
tagline:          'Welcome to my soapbox'
description:      'Rants and Raves about software and parenting'
url:              http://github.com/unchris/unchris.github.io
baseurl:          /

author:
  name:           'Chris Cameron'
  url:            https://unchris.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/unchris/unchris.github.io

# about me
linkedin:         https://www.linkedin.com/in/chrisjohncameron/
gitlab:           https://www.gitlab.com/unchris
stackoverflow:    https://www.stackoverflow.com/u/44484